----------------
<h2 style="color:blue;"><b>NumPy Structures & Operations</b></h2>

-------------------

<ul style="color:SlateBlue;">
    <li>NumPy module supports fast numerical operation within Python and forms the basis for the Pandas module.</li>
    <li>It builds around a new, n-dimensional array (ndarray) data structure that provides numerical computations.</li>
    <li>This data type for objects stored in the array can be specified at creation time, but the array is homogenous.</li>
    <li>This array can be used to represent a vector (one-dimensional set of numerical values) or matrix (multiple-dimensional set of vectors).</li>
    <li>Furthermore, NumPy provides</li>
    <ul style="color:DodgerBlue;">
        <li>additional benefits built on top of the array object, including:</li>
        <ul>
            <li>masked arrays_, </li>
            <li>_universal functions_, </li>
            <li>_sampling from random distributions_, </li>
        </ul>
        <li>and support for </li>
        <ul>
            <li>_user-defined, 	arbitrary data-types that allow the array to become an efficient, multi-dimensional generic data container.</li>
        </ul>
    </ul>
    </ul>

-----------------------------

In [1]:
## Compare the times between list and numpy array

import math
import numpy as np

size = 100000
delta = 1.0E-2          # 0.01

aList = [(x + delta) for x in range(size)]
anArray = np.arange(size) + delta

print(aList[:6])
print(anArray[:6])

print("\nTime to process list:")
%timeit [math.sin(x) for x in aList]
%timeit [math.cos(x) for x in aList]
%timeit [math.log(x) for x in aList]

print("\nTime to process numpy arrary:")
%timeit np.sin(anArray)
%timeit np.cos(anArray)
%timeit np.log10(anArray)


[0.01, 1.01, 2.01, 3.01, 4.01, 5.01]
[0.01 1.01 2.01 3.01 4.01 5.01]

Time to process list:
12.3 ms ± 238 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.1 ms ± 295 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
17.5 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Time to process numpy arrary:
629 µs ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
642 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
468 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


---------------------------------------------------
<h3 style="color:blue;">Creating an Array with NumPy</h3>
<ul style="color:SlateBlue;">
    <li>NumPy arrays, instances of the ndarray class, are data structures that can be created in a number of different ways.</li>
    <li>You can create an array from an existing Python list or tuple, or use one of the many built-in NumPy convenience methods:</li>
    <ul style="color:DodgerBlue;">
        <li>empty: Creates a new array whose elements are uninitialized.</li>
        <li>zeros: Creates a new array whose elements are initialized to zero.</li>
        <li>ones: Creates a new array whose elements are initialized to one.</li>
        <li>empty_like: Creates a new array whose size matches the input array and whose values are uninitialized.</li>
        <li>zero_like: Creates a new array whose size matches the input array and whose values are initialized to zero.</li>
        <li>ones_like: Creates a new array whose size matches the input array and whose values are initialized to unity.</li>
    </ul>
    </ul>
    
-----------------


In [2]:
## Create an array with NumPy Example #1
# Make and print out simple NumPy arrays
import numpy as np

print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

print("\n", np.empty(10))                 # all entries are un-initialized
print("\n", np.zeros(10))                 # all entries set to zero
print("\n", np.ones(10))                  # all entries set to one
print("\n", np.ones_like(np.arange(10)))  # all entries set to unity with size same as input array


[0 1 2 3 4 5 6 7 8 9]

 [2.33419537e-312 9.76118064e-313 2.35541533e-312 1.03977794e-312
 8.48798317e-313 2.33419537e-312 2.41907520e-312 2.05833592e-312
 8.70018275e-313 1.24610927e-306]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [1 1 1 1 1 1 1 1 1 1]


In [3]:
## Create an array with NumPy Example #2
import math
import numpy as np

size = 100000
delta = 1.0E-2

## Create list of elments by operation of list
aList = [(x + delta) for x in range(size)]
print(type(aList))
print(aList[0:4], aList[-3:], "\n")


## Create array of elements with NumPy
anArray = np.arange(size) + delta
print(type(anArray))
print(anArray[0:4], anArray[-3:])


<class 'list'>
[0.01, 1.01, 2.01, 3.01] [99997.01, 99998.01, 99999.01] 

<class 'numpy.ndarray'>
[0.01 1.01 2.01 3.01] [99997.01 99998.01 99999.01]


In [4]:
## Demonstrate linear and logarthmic array creation.
import numpy as np

print(np.arange(10))
print(np.arange(3, 10, 2), "\n")

print("Linear space bins [0, 10] = {}\n".format(np.linspace(0, 10, 4)))

print("Default linspace bins = {}\n".format(len(np.linspace(0,10))))

print("Log space bins [0, 1] = {}\n".format(np.logspace(0, 1, 4)))       # 10^(1/3) = 2.15444

print("Default linspace bins = {}\n".format(len(np.logspace(1, 10))))


[0 1 2 3 4 5 6 7 8 9]
[3 5 7 9] 

Linear space bins [0, 10] = [ 0.          3.33333333  6.66666667 10.        ]

Default linspace bins = 50

Log space bins [0, 1] = [ 1.          2.15443469  4.64158883 10.        ]

Default linspace bins = 50



-------------
<h3 style="color:blue;">Indexing Arrays – access elements in an array</h3>

------------------

In [5]:
## Create an initial array with elements from 0 ~ 8 inclusively
import numpy as np
aData = np.arange(9)
print("Original Array = ", aData)

## Assign values to specific elements
aData[1] = 3              # assign 3 to the second element
aData[3:5] = 4            # assign 4 to the fourth and fifth elements
aData[0:6:2] *= -1        # multiple the 1st, 3rd, and 5th element 

print("\nNew Array = ", aData)


Original Array =  [0 1 2 3 4 5 6 7 8]

New Array =  [ 0  3 -2  4 -4  5  6  7  8]


--------------
<h3 style="color:blue;">Special Indexing</h3>
<ul style="color:SlateBlue;">
    <li>Access the elements by index array & access by Boolean mask array</li>
    </ul>
    
------------------------


In [6]:
## Demonstrate access by index array and by Boolean mask array
import numpy as np
aData = np.arange(10, 20)

## index array
print("Original array: ", aData)
print("\nIndex Access: ", aData[np.array([1, 3, 5, 7, 2])])

## masking array
print("\nMask Array: ", aData > 4)

## Change the values by using the mask
aData[aData > 14] = -1.0
print("New Array: ", aData)

print("Masked Array: ", aData[aData > 12])


Original array:  [10 11 12 13 14 15 16 17 18 19]

Index Access:  [11 13 15 17 12]

Mask Array:  [ True  True  True  True  True  True  True  True  True  True]
New Array:  [10 11 12 13 14 -1 -1 -1 -1 -1]
Masked Array:  [13 14]


-----------------------
<h3 style="color:blue;">Summary Functions</h3>
<ul style="color:SlateBlue;">
    <li>Statistical measures (mean, median, var, std, min, and max)</li>
    <li>Total sum or product (sum, and prod)</li>
    <li>Running sum and product (cumsum, and cumprod)</li>
    </ul>
    <p style="color:orange;">Refered to this link for reference: </p><span>https://numpy.org/doc/stable/reference/arrays.ndarray.html</span>
    
------------------------------------------


In [7]:
## Demonstration of Summary Functions
## Make an array = [1, 2, 3, 4, 5]
import numpy as np
anArray = np.arange(1, 6)
print("Original array:  ", anArray, "\n")

print("Mean value = {}".format(np.mean(anArray)))
print("Median value = {}".format(np.median(anArray)))
print("Variance = {}".format(np.var(anArray)))
print("Std. Deviation = {}\n".format(np.std(anArray)))

print("Minimum value = {}".format(np.min(anArray)))
print("Maximum value = {}\n".format(np.max(anArray)))

print("Sum of all values = {}".format(np.sum(anArray)))
print("Running cumulative sum of all values = {}\n".format(np.cumsum(anArray)))

print("Product of all values = {}".format(np.prod(anArray)))
print("Running product of all values = {}\n".format(np.cumprod(anArray)))


Original array:   [1 2 3 4 5] 

Mean value = 3.0
Median value = 3.0
Variance = 2.0
Std. Deviation = 1.4142135623730951

Minimum value = 1
Maximum value = 5

Sum of all values = 15
Running cumulative sum of all values = [ 1  3  6 10 15]

Product of all values = 120
Running product of all values = [  1   2   6  24 120]



-------------------
<h3 style="color:blue;">Multi-Dimensional Array</h3>
<ul style="color:SlateBlue;">
    <li>Higher dimensional arrays can be created in the same way that a single dimensional array</li>
    <li>First create a one dimensional arrays with the correct number of elements and then use the reshape function from NumPy to create the n-dimensional array.</li>
    </ul>
    
------------------------


In [10]:
## Example to create a 4x5 matrix
import numpy as np

# Make a one 20 element one-dimensional array
d20 = np.arange(20)
print(d20, "\n")

# Reshape to a 4 x 5 array
mat45 = d20.reshape(4, 5)         # reshape as a 4x5 matrix
print(mat45)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
## Example to create a 3x4x5 matrix
import numpy as np

# Make a one 60 element one-dimensional array
d60 = np.arange(1,61)
print(d60, "\n")

# Reshape to a 3x4x5 array
mat345 = d60.reshape(3, 4, 5)
print(mat345, "\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60] 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]] 



In [1]:
## Demonstration of Summary Functions on a 2-dimensional Matrix
## Make a 4x4 matrix
import numpy as np
anMat = np.arange(1,17).reshape(4,4)
print("Original array:\n", anMat)

print("\nMean value = {}".format(np.mean(anMat)))
print("Median value = {}".format(np.median(anMat)))
print("Variance = {}".format(np.var(anMat)))
print("Std. Deviation = {0:.6f}".format(np.std(anMat)))

print("\nMinimum value = {}".format(np.min(anMat)))
print("Maximum value = {}".format(np.max(anMat)))

print("\nSum of all values = {}".format(np.sum(anMat)))
print("\nRunning cumulative sum of all values:\n{}".format(np.cumsum(anMat)))
print("\nRunning cumulative sum for each column over rows:\n{}".format(np.cumsum(anMat, axis=0)))

print("\nProduct of all values = {}".format(np.prod(anMat)))
print("\nRunning product of all values:\n{}".format(np.cumprod(anMat)))
print("\nRunning product for each row over columns:\n{}".format(np.cumprod(anMat, axis=1)))


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Mean value = 8.5
Median value = 8.5
Variance = 21.25
Std. Deviation = 4.609772

Minimum value = 1
Maximum value = 16

Sum of all values = 136

Running cumulative sum of all values:
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136]

Running cumulative sum for each column over rows:
[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]
 [28 32 36 40]]

Product of all values = 2004189184

Running product of all values:
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280 2004310016 2004189184]

Running product for each row over columns:
[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]
 [   13   182  2730 43680]]


--------------
<h3 style="color:blue;">Create special two-dimensional array</h3>

--------------------------------


In [12]:
## Create special two-dimensional arrays

print("Matrix will be 4 x 4.\n", np.eye(4))    # Identity matrix
print("\nMatrix will be 4 x 4.\n", np.diag(np.arange(4), 0))
print("\nMatrix will be 5 x 5.\n", np.diag(np.arange(4), 1))
print("\nMatrix will be 5 x 5.\n", np.diag(np.arange(4), -1))


Matrix will be 4 x 4.
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matrix will be 4 x 4.
 [[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]

Matrix will be 5 x 5.
 [[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]

Matrix will be 5 x 5.
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


---------------
<h3 style="color:blue;">Slicing Multi-Dimensional Arrays</h3>
<ul style="color:SlateBlue;">
    <li>Multi-dimensional arrays can be sliced (or indexed); the only trick is to remember the proper ordering for the elements.</li>
    <li>Each dimension is differentiated by a comma in the slicing operation.</li>
    <li>A two-dimensional array is sliced with [start1:end1, start2:end2],</li>
    <li>A  three-dimensional array is sliced with [start1:end1, start2:end2. start3:end3], continuing on with higher dimensions.</li>
    </ul>
    
-----------------------


In [13]:
## Demonstration on two-dimensional slicing
import numpy as np
aData = np.arange(1,13).reshape((3,4))

print("3 x 4 array = \n", aData)

print("\nSlice in first dimension (row 1): ", aData[0])
print("\nSlice in first dimension (row 3): ", aData[2])

print("\nSlice in second dimension (col 1): ", aData[:, 0])
print("\nSlice in second dimension (col 3): ", aData[:, 2])

print("\nSlice in first and second dimension: ", aData[0:2, 1:3])

print("\nDirect Element access: ", aData[0,1])


3 x 4 array = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Slice in first dimension (row 1):  [1 2 3 4]

Slice in first dimension (row 3):  [ 9 10 11 12]

Slice in second dimension (col 1):  [1 5 9]

Slice in second dimension (col 3):  [ 3  7 11]

Slice in first and second dimension:  [[2 3]
 [6 7]]

Direct Element access:  2


In [1]:
## Demonstration on three-dimensional slicing
import numpy as np
aData = np.arange(27).reshape((3, 3, 3))

print("3 x 3 x 3 array = \n", aData)
print("\nSlice in first dimension (first x axis slice):\n", aData[0])

print("\nSlice in first and second dimension: ", aData[0, 1])

print("\nSlice in first dimension (third x axis slice):\n", aData[2])

print("\nSlice in second dimension (first y axis slice):\n", aData[:, 0])
print("\nSlice in second dimension (third y axis slice):\n", aData[:, 2])

print("\nSlice in first and second dimension: ", aData[0:1, 1:2])

print("\nSlice in first and second dimension:\n", aData[0, 1])
print("\nSlice in first and third dimension: ", aData[0, : ,1])
print("\nSlice in first, second, and third dimension: ", aData[0:1, 1:2, 2:])

print("\nDirect element access: ", aData[0, 1, 2])


3 x 3 x 3 array = 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Slice in first dimension (first x axis slice):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Slice in first and second dimension:  [3 4 5]

Slice in first dimension (third x axis slice):
 [[18 19 20]
 [21 22 23]
 [24 25 26]]

Slice in second dimension (first y axis slice):
 [[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]

Slice in second dimension (third y axis slice):
 [[ 6  7  8]
 [15 16 17]
 [24 25 26]]

Slice in first and second dimension:  [[[3 4 5]]]

Slice in first and second dimension:
 [3 4 5]

Slice in first and third dimension:  [1 4 7]

Slice in first, second, and third dimension:  [[[5]]]

Direct element access:  5


--------------
<h3 style="color:blue;">Special Indexing – Boolean Mask Access</h3>

-----------------------


In [14]:
## Demonstration of a multi-dimensional index array
import numpy as np

# Two-dimensional array
aData = np.arange(10).reshape((2, 5))

print("\nStarting array:\n", aData)
print("\nIndex Array access:\n", aData[np.array([0, 1]) , np.array([3, 4])])
print("\nMore Index Array access:\n", aData[np.array([0, 0, 1]), np.array([2, 4, 3])])



Starting array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Index Array access:
 [3 9]

More Index Array access:
 [2 4 8]


In [15]:
## Demonstrate Boolean mask access - Two-dimensional example.
import numpy as np

aData = np.arange(1,26).reshape((5, 5))
print("\n Starting Array: \n", aData)

# Build a mask that is True for all even elements with value greater than four
mask1 = (aData > 8)
mask2 = (aData % 2 == 0)
print("\nMask 1:\n", mask1)
print("\nMask 2:\n", mask2)

# We use the logical_and ufunc here, but it is described later
mask = np.logical_and(mask1, mask2)
print("\nMask :\n", mask)

print("\nMasked Array :\n", aData[mask])
aData[mask] *= -2            # only those that masked as true be modified
print("\nNew Array :\n", aData)    



 Starting Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Mask 1:
 [[False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

Mask 2:
 [[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

Mask :
 [[False False False False False]
 [False False False False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

Masked Array :
 [10 12 14 16 18 20 22 24]

New Array :
 [[  1   2   3   4   5]
 [  6   7   8   9 -20]
 [ 11 -24  13 -28  15]
 [-32  17 -36  19 -40]
 [ 21 -44  23 -48  25]]


--------------------
<h3 style="color:blue;"><b>Student Practice #1</b></h3>
<p style="color:SlateBlue;">In the empty Code cell below, write and execute code to make a four by five matrix that contains the integers 2, 4, 6, ..., 40. Slice and display:</p>
<ol style="color:DodgerBlue;">
    <li>the third row,</li>
    <li>the fourth column, and</li>
    <li>the element at the position (4, 4).</li>
    </ol>
    
-------------------------

In [4]:
import numpy as np

infile = np.arange(2, 41, 2).reshape(4, 5)
print("\n Starting Array:\n", infile)

print("\n The third row:\n", infile[2])
print("\n The fourth column:\n", infile[:, 3])
print("\n The element of position at (4, 4):", infile[3, 3])


 Starting Array:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]

 The third row:
 [22 24 26 28 30]

 The fourth column:
 [ 8 18 28 38]

 The element of position at (4, 4): 38


----------------------
<h3 style="color:blue;"><b>Student Practice #2</b></h3>
<p style="color:SlateBlue;">In the empty Code cells below, write and execute code to make a four by four matrix that contains the integers 1 through 16, then perform the following:</p>
<ol style="color:DodgerBlue;">
    <li>Add five to the first row, ten to the second row, fifteen to the third row, twenty to the fourth row, and display the resulting matrix. </li>
    <li>Next apply the cos function to the odd rows, and the sin function to the even rows, and display the resulting matrix.</li>
    <li>Finally, compute and display the cumulative sum for each row, and the cumulative product for each column.</li>
    </ol>

----------------------------------

In [23]:
import numpy as np
import numpy.ma as ma

file = np.arange(1, 17).reshape(4, 4)
print("\n Original Array:\n", file)


##Add 5 to the first row
mask = ma.asarray(file, dtype=bool)
mask[:,:] = False
mask[0] = True
file[mask] += 5
print("\n Matrix after add 5 to the first row \n{}".format(file))

##Add 10 to the second row
mask = ma.asarray(file, dtype=bool)
mask[:,:] = False
mask[1] = True
file[mask] += 10
print("\n Matrix after add 10 to the second row\n {}".format(file))

##Add 15 to the third row
mask = ma.asarray(file, dtype=bool)
mask[:,:] = False
mask[2] = True
file[mask] += 15
print("\n Matrix after add 15 to the third row\n {}".format(file))

##Add 20 to the fourth row
mask = ma.asarray(file, dtype=bool)
mask[:,:] = False
mask[3] = True
file[mask] += 20
print("\n Matrix after add 20 to the third row\n {}".format(file))

##Question 2
print("\n" + "~*-*-*-*"*10 + "\n")
aData = np.arange(1, 17).reshape(4, 4).astype(float)
mask = (aData > 16)
mask[0] = True
mask[2] = True
aData[mask] = np.cos(aData[mask])
print("\n Matrix after applying cos to the first and third row \n {}".format(aData))

mask[:,:] = False 
mask[1] = True
mask[3] = True
aData[mask] = np.sin(aData[mask])
print("\n Matrix after applying sin to the second and fourth row \n {}".format(aData))

##Question 3
print("\n" + "~*-*-*-*"*10 + "\n")
print("\n The cumulative sum for each row\n {}".format(np.cumsum(aData, axis=1)))
print("\nThe cumulative product for each column: \n{}".format(np.cumprod(aData, axis=0)))


 Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Matrix after add 5 to the first row 
[[ 6  7  8  9]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Matrix after add 10 to the second row
 [[ 6  7  8  9]
 [15 16 17 18]
 [ 9 10 11 12]
 [13 14 15 16]]

 Matrix after add 15 to the third row
 [[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [13 14 15 16]]

 Matrix after add 20 to the third row
 [[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [33 34 35 36]]

~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*~*-*-*-*


 Matrix after applying cos to the first and third row 
 [[ 5.40302306e-01 -4.16146837e-01 -9.89992497e-01 -6.53643621e-01]
 [ 5.00000000e+00  6.00000000e+00  7.00000000e+00  8.00000000e+00]
 [-9.11130262e-01 -8.39071529e-01  4.42569799e-03  8.43853959e-01]
 [ 1.30000000e+01  1.40000000e+01  1.50000000e+01  1.60000000e+01]]

 Matrix after applying sin to the second and fourth row 
 [[ 0.54030231 -0.41614684 -0.9899925  -0.6536436