----------------
<h2 style="color:blue;"><b>NumPy Structures & Operations</b></h2>

-------------------

--------------------
<h3 style="color:blue;"><b>Student Practice #1</b></h3>
<p style="color:SlateBlue;">In the empty Code cell below, write and execute code to make a four by five matrix that contains the integers 2, 4, 6, ..., 40. Slice and display:</p>
<ol style="color:DodgerBlue;">
    <li>the third row,</li>
    <li>the fourth column, and</li>
    <li>the element at the position (4, 4).</li>
    </ol>
    
-------------------------

In [1]:
import numpy as np

## Create a 4x5 Matrix contains the integers 2, 4, 6, ...., 40
aData = np.arange(2, 41, 2).reshape(4, 5)
print("Initial Matrix:\n{}".format(aData))

## Slice and display the third row
print("\nThe 3rd row of the matrix:\n{}".format(aData[2]))

## Slice and display the fourth column
print("\nThe 4th column of the matrix:\n{}".format(aData[:, 3]))

## Slice and display the element at the position (4, 4).
print("\nThe element at (4,4) of the matrix: {}".format(aData[3,3]))


Initial Matrix:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]

The 3rd row of the matrix:
[22 24 26 28 30]

The 4th column of the matrix:
[ 8 18 28 38]

The element at (4,4) of the matrix: 38


----------------------
<h3 style="color:blue;"><b>Student Practice #2</b></h3>
<p style="color:SlateBlue;">In the empty Code cells below, write and execute code to make a four by four matrix that contains the integers 1 through 16, then perform the following:</p>
<ol style="color:DodgerBlue;">
    <li>Add five to the first row, ten to the second row, fifteen to the third row, twenty to the fourth row, and display the resulting matrix. </li>
    <li>Next apply the cos function to the odd rows, and the sin function to the even rows, and display the resulting matrix.</li>
    <li>Finally, compute and display the cumulative sum for each row, and the cumulative product for each column.</li>
    </ol>

----------------------------------

In [1]:
## Add five to the first row, ten to the second row, fifteen to the third row, 
## twenty to the fourth row, and display the resulting matrix.
import numpy as np
import numpy.ma as ma

## Create the 4x4 matrix that contains 1 to 16
aData = np.arange(1, 17).reshape(4,4)
print("Initial Matrix:\n{}".format(aData))

## Add 5 to the 1st row
mask = ma.asarray(aData, dtype=bool)    # you may just create another matrix of the same size
mask[:,:] = False     # set all entries to False
mask[0] = True        # set the entries on 1st row to True
aData[mask] += 5
print("\nMatrix after 1st row +5 :\n{}".format(aData))

## Add 10 to the 2nd row
mask[:,:] = False
mask[1] = True
aData[mask] += 10
print("\nMatrix after 2nd row +10 :\n{}".format(aData))

## Add 15 to the 3rd row
mask[:,:] = False
mask[2] = True
aData[mask] += 15
print("\nMatrix after 3rd row +15 :\n{}".format(aData))

## Add 20 to the 4th row
mask[:,:] = False
mask[3] = True
aData[mask] += 20
print("\nMatrix after 4th row +20 :\n{}".format(aData))

## Appy cos function to odd rows
aData = np.arange(1,17).reshape(4,4).astype(float)   # have the original matrix in float
print("\n{0}-\n\nInitial Matrix:\n{1}".format(15*"- * ", aData))
mask = (aData > 999999) # alternative way to mask be false, assume 999999 > all values in aData
mask[0] = True          # set odd row to True
mask[2] = True          # set odd row to True
aData[mask] = np.cos(aData[mask])
print("\nMatrix after apply sin on row 1 & 3 :\n{}".format(aData))

## Appy sin function to even rows
mask[:,:] = False
mask[1] = True
mask[3] = True
aData[mask] = np.sin(aData[mask])
print("\nMatrix after appy cos on row 2 & 4 :\n{}".format(aData))

## compute and display the cumulative sum for each row, and
## the cumulative product for each column.
aData = np.arange(1,17).reshape(4,4)          # have the original matrix
print("\n{0}-\n\nInitial Matrix:\n{1}".format(15*"- * ", aData))

# cummulative sum on each row over the columns
print("\nThe cumulative sum for each row: \n{}".format(np.cumsum(aData, axis=1)))

# cummulative product on each column over the rows
print("\nThe cumulative product for each column: \n{}".format(np.cumprod(aData, axis=0)))


Initial Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 1st row +5 :
[[ 6  7  8  9]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 2nd row +10 :
[[ 6  7  8  9]
 [15 16 17 18]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 3rd row +15 :
[[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [13 14 15 16]]

Matrix after 4th row +20 :
[[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [33 34 35 36]]

- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * -

Initial Matrix:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Matrix after apply sin on row 1 & 3 :
[[ 5.40302306e-01 -4.16146837e-01 -9.89992497e-01 -6.53643621e-01]
 [ 5.00000000e+00  6.00000000e+00  7.00000000e+00  8.00000000e+00]
 [-9.11130262e-01 -8.39071529e-01  4.42569799e-03  8.43853959e-01]
 [ 1.30000000e+01  1.40000000e+01  1.50000000e+01  1.60000000e+01]]

Matrix after appy cos on row 2 & 4 :
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [-0.95892427 

In [2]:
## Alternative Solution - provided that there exist consistent pattern on the entries ##

import numpy as np

## Create two matrix of the same size
control = np.arange(1, 17).reshape(4,4)
aData = np.arange(1, 17).reshape(4,4)
print("Initial Matrix:\n{}".format(aData))

## Add 5 to 1st row, 10 to 2nd, 15 to 3rd, and 20 to 4th row
mask = (control <= 4)
aData[mask] += 5
print("\nMatrix after 1st row +5 :\n{}".format(aData))

mask = np.logical_and(control >= 5, control <= 8)
aData[mask] += 10
print("\nMatrix after 2nd row +10 :\n{}".format(aData))

mask = np.logical_and(control >= 9, control <= 12)
aData[mask] += 15
print("\nMatrix after 3rd row +15 :\n{}".format(aData))

mask = (control >= 13)
aData[mask] += 20
print("\nMatrix after 4th row +20 :\n{}".format(aData))

## Appy cos function to odd rows and sin function to even rows
aData = np.arange(1,17).reshape(4,4).astype(float)
print("\n{0}-\n\nInitial Matrix:\n{1}".format(15*"- * ", aData))
mask1 = (control <= 4)
mask2 = np.logical_and(control >= 9, control <= 12)
mask = np.logical_or(mask1, mask2)
aData[mask] = np.cos(aData[mask])
print("\nMatrix after apply cos on row 1 & 3 :\n{}".format(aData))

mask1 = np.logical_and(control >= 5, control <= 8)
mask2 = (control >= 13)
mask = np.logical_or(mask1, mask2)
aData[mask] = np.sin(aData[mask])
print("\nMatrix after apply sin on row 2 & 4 :\n{}".format(aData))


Initial Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 1st row +5 :
[[ 6  7  8  9]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 2nd row +10 :
[[ 6  7  8  9]
 [15 16 17 18]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix after 3rd row +15 :
[[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [13 14 15 16]]

Matrix after 4th row +20 :
[[ 6  7  8  9]
 [15 16 17 18]
 [24 25 26 27]
 [33 34 35 36]]

- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * -

Initial Matrix:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Matrix after apply cos on row 1 & 3 :
[[ 5.40302306e-01 -4.16146837e-01 -9.89992497e-01 -6.53643621e-01]
 [ 5.00000000e+00  6.00000000e+00  7.00000000e+00  8.00000000e+00]
 [-9.11130262e-01 -8.39071529e-01  4.42569799e-03  8.43853959e-01]
 [ 1.30000000e+01  1.40000000e+01  1.50000000e+01  1.60000000e+01]]

Matrix after apply sin on row 2 & 4 :
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [-0.95892427