--------------------------------------------------

<h2 style="color:blue;"><b>Functions</b></h2>

<h3 style="color:blue;"><b>Boolean- and List-Valued Functions</b></h3>
<ul style="color:DodgerBlue;">
    <li>The values returned not just only be numbers or strings.</li>
    <li>It can return any type of value or even not return anything (i.e. no return statements).</li>
    </ul>
    
-----------------------------------------

In [1]:
## function return a boolean-value
def isVowelWord(word):
    word = word.upper()
    vowels = ("A", "E", "I", "O", "U")   # list of vowels
    for vowel in vowels:
        if vowel not in word:
            return False
    return True

In [3]:
## Determine if a given word contains every vowel.
word = input("Enter a word / sentence:  ")
if isVowelWord(word):
    print(word, " - contains every vowel")
else:
    print(word, " - does not contain every vowel")

Enter a word / sentence:  i love python
i love python  - does not contain every vowel


In [4]:
## function return a list-value
def occuringVowels(word):
    word = word.upper()
    vowels = ("A", "E", "I", "O", "U")   # list of vowels
    includedVowels = []
    for vowel in vowels:
        if (vowel in word) and (vowel not in includedVowels):
            includedVowels.append(vowel)
    return includedVowels    

In [5]:
## Determine the vowels appearing in a word
word = input("Enter a word: ")
listOfVowels = occuringVowels(word)
stringOfVowels = " ".join(listOfVowels)
print("The following vowels occur in the word {}: {}".format(word, stringOfVowels))

Enter a word: Hibiscus is a kind of flower.
The following vowels occur in the word Hibiscus is a kind of flower.: A E I O U


-----------------------------

<h3 style="color:blue;"><b>Scope of Variable</b></h3>
<ul style="color:DodgerBlue;">
    <li>A variable created inside a function can only be accessed by statements inside that function, and ceases to exist when the function is exited.</li>
    <li>The variable is said to be local to the function or to have local scope.</li>
    <li>The same is true for the function’s parameters.
If variables created in two different functions have the same name, they have no relationship to each other; they are treated as completely different variables.</li>
    </ul>
    
-----------------------------

In [1]:
## program segment that demo the scope of variable
name = "Fred"

def main():
    global name
    otherName = getName()
    name += otherName
    print (name)
    
def getName():
    name = "eric"
    return name

main()

Frederic


----------------------

<h3 style="color:blue;"><b>Functions Returning Multiple Values</b></h3>
<ul style="color:DodgerBlue;">
    <li>Functions can return any type of object, not just a number, string, or Boolean value.</li>
    <li>The follow example is an instance of a function that return a tuple.</li>
    </ul>
    
------------------------

In [2]:
INTEREST_RATE = 0.04      # annual rate of interest

def main():
    ## Calculate the balance and interest earned from a savings account.
    principal = eval(input("Enter the amount of the deposit: "))
    numberOfYears = eval(input("Enter the number of years: "))
    (bal, intEarned) = balanceAndInterest(principal, numberOfYears)
    print("\nBalance: ${0:,.2f} ".format(bal), end="")
    print("Interest Earned: ${0:,.2f}".format(intEarned))

def balanceAndInterest(prin, numYears):
    balance = prin * ((1 + INTEREST_RATE) ** numYears)
    interestEarned = balance - prin
    return (balance, interestEarned)

main()

Enter the amount of the deposit: 80000
Enter the number of years: 2

Balance: $86,528.00 Interest Earned: $6,528.00


----------------------

<h3 style="color:blue;"><b>Functions Calling Other Functions</b></h3>
<ul style="color:DodgerBlue;">
    <li>A function can call another function.</li>
    <li>When the called function terminates (that is, after a return statement or the last statement of the called function is executed), the control returns to the place in the calling function just after where the function call occurred.</li>
    </ul>




<h3 style="color:blue;"><b>Function that Calling Itself</b></h3>
<ul style="color:DodgerBlue;">
    <li>Function that calling itself is known as recursive function.</li>
    <li>It is a very powerful function to solve some recurrence instances.</li>
    <li>Example:</li>
    <ol style="color:SlateBlue;">
        <li>determine a factorial</li>
        <li>determine the game tower-of-hanoi</li>
    </ol>
    </ul>
    
-----------------------------------------------

In [3]:
## factorial function, ## this function accept any non-negative, 
## including zero with 0! = 1
def factorial(n):
    if n <= 1:
        print(1, end=" ")
        return 1
    else:
        print("{} x".format(n), end=" ")
        return(factorial(n-1))

In [4]:
num = eval(input("Enter a non-negative, including zero: "))
print("{}! = ".format(num), end="")
factorial(num)
print("\n")


Enter a non-negative, including zero: 7
7! = 7 x 6 x 5 x 4 x 3 x 2 x 1 



In [5]:
## The game tower-of-hanoi
def towerOfHanoi(nDisc, fromP, toP, tempP):
    if nDisc <= 1:
        print("Move disc {} from {} to {}".format(nDisc, fromP, toP))
    else:
        towerOfHanoi(nDisc-1, fromP, tempP, toP)
        print("Move disc {} from {} to {}".format(nDisc, fromP, toP))
        towerOfHanoi(nDisc-1, tempP, toP, fromP)

In [6]:
towerOfHanoi(4, "A", "C", "B")

Move disc 1 from A to B
Move disc 2 from A to C
Move disc 1 from B to C
Move disc 3 from A to B
Move disc 1 from C to A
Move disc 2 from C to B
Move disc 1 from A to B
Move disc 4 from A to C
Move disc 1 from B to C
Move disc 2 from B to A
Move disc 1 from C to A
Move disc 3 from B to C
Move disc 1 from A to B
Move disc 2 from A to C
Move disc 1 from B to C


----------------------

<h3 style="color:blue;"><b>Library Modules</b></h3>
<ul style="color:DodgerBlue;">
    <li>A variation of the import statement is</li>
    <span style="color:white;">.....</span><span style="color:brown;">from moduleName import *</span><br>
<li>After such a statement has been executed, any function from the module can be used directly without having to prepend it with the module name and a period.</li> 
    <li>This variation is most often employed when a program uses many functions from the module.</li>
    </ul>
    
----------------------------

In [3]:
import numpy as np   ## module of mathematical functions
import pandas as pd
import seaborn as sns
import scipy.stats as sts
import matplotlib as mpl
import matplotlib.pyplot as plt
import math
import random
import csv
import sys

In [4]:
student = ("Peter", "Calvin", "Steven", "Alan", "Debbie", \
          "Zoo", "Queenie", "Betty", "Don", "Ban", \
          "Lancy", "Mandy", "Terry", "Wendy", "Grace")


In [5]:
random.choice(student)

'Debbie'

In [6]:
random.choice(student)

'Don'

In [7]:
random.choice(student)

'Don'

In [8]:
math.floor(3.1417)

3

In [9]:
math.ceil(3.1417)

4

In [10]:
math.pow(3, 4)

81.0

In [11]:
np.arange(2,10) # create a list the have values from 2 to 10-1 inclusively

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.full((3,4), 5) # create a 3x4 matrix that fill with 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
np.linspace(0,2,11) # evenly determine 11-1 segments from range 0 ~ 2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

---------------------------

<h3 style="color:red;"><b>Student Practice</b></h3>
<p style="color:SlateBlue;">In the empty cells below, write a pay-raise program that enter a person's name,
and current monthly salary, and then displays the person's monthly salary next year (i.e. salary that after increment).
    People earning less than mop 30,000 a month will receive a 5% raise, and those earning mop 30,000 or more will receive a raise of mop 1,800 plus 2% of the amount over mop 30,000. Use functions for input and output, and a function to calculate the new salary.
</p>

-------------------------------

In [20]:
def salaryIncre(sal):
    if sal < 30000:
        incredsalary = sal * (1+0.05)
        print("your monthly salary next year will be ${}".format(incredsalary))
    else:
        incredsalary = sal + 1800 + (sal - 30000)*0.02
        print("your monthly salary next year will be ${}".format(incredsalary))

In [21]:
name_ = input("please input your name: ")
salary_ = eval(input('please input your monthly salary: '))
salaryIncre(salary_)

please input your name: Duke
please input your monthly salary: 33333
your monthly salary next year will be $35199.66


---------------------------

<h3 style="color:red;"><b>Student Practice - CHALLENGE QUESTION</b></h3>
<p style="color:SlateBlue;">In the empty cell below, write a function to return the nth  Fibonacci number.</p>
<p style="color:slateBlue;">The Fibonacci Sequence is the series of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ..., the 1st term returns a 0, the 2nd returns a 1, and the 3rd term returns a 1, the 4th term returns a 2, and so on.
</p>

-------------------------------

In [44]:
## function fibonacci accept a non-negative and 
## return the nth term of the fibonacci number
def fibonacci(num):
    a = 0
    b = 1
    if num == 1:
        print('fibonacci = 0')
    if num < 4:
        print('fibonacci = {}'.format(b))
    else:
        a, b = 1, 1
        b = a + b
        while num >= 4:
            a, b = b, a+b
            num -=1
        print('fibonacci = {}'.format(a))

fibonacci(101)

fibonacci = 354224848179261915075


In [17]:
## get the nth fibonacci number
fibonacci(7)

fibonacci = 8


---------------------

<h3 style="color:red;"><b>Student Practice - CHALLENGE QUESTION</b></h3>
<p style="color:SlateBlue;">In the empty cell below, write a function to generate the Fibonacci sequence.<br>
The Fibonacci sequence is the series of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ....</p>

---------------------

In [41]:
def fib_recur(n):
    assert n >= 0, "n > 0"
    if n <= 1:
        return n
    return fib_recur(n-1) + fib_recur(n-2)

for i in range(1, 20):
    print(fib_recur(i), end=' ')

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 

please input nth Fibonacci number you want to know: 7
6765
