--------------------------------------------------

<h2 style="color:blue;"><b>Functions</b></h2>

<h3 style="color:blue;"><b>Boolean- and List-Valued Functions</b></h3>
<ul style="color:DodgerBlue;">
    <li>The values returned not just only be numbers or strings.</li>
    <li>It can return any type of value or even not return anything (i.e. no return statements).</li>
    </ul>
    
-----------------------------------------

In [ ]:
## function determine whether the input word, contain ALL vowels
## and return a boolean-value to indicate falsity of the case

def isVowelWord(word):
    word = word.upper()
    vowels = ("A", "E", "I", "O", "U")   # list of vowels
    for vowel in vowels:
        if vowel not in word:  # just one of the vowels not exists, return false
            return False
    return True


In [ ]:
## This function prompt the user to input a word / sentence and
## call the function isVowelWord to determine it contains all vowels.

word = input("Enter a word / sentence:  ")
if isVowelWord(word):
    print(word, " - contains every vowel")
else:
    print(word, " - does not contain every vowel")
    

In [ ]:
## This function returns the vowels that contained in the input words
## and return a list-value

def occuringVowels(word):
    word = word.upper()
    vowels = ("A", "E", "I", "O", "U")   # list of vowels
    includedVowels = []
    for vowel in vowels:
        if (vowel in word) and (vowel not in includedVowels):
            includedVowels.append(vowel)   # append the vowel found into the list
    return includedVowels 


In [ ]:
## This function prompt the user to input a word and call the
## function isVowelWord to determine it contains all vowels.

## Determine the vowels appearing in a word
word = input("Enter a word: ")
listOfVowels = occuringVowels(word)
stringOfVowels = " ".join(listOfVowels)
print("The following vowels occur in the word {}: {}".format(word, stringOfVowels))


-----------------------------

<h3 style="color:blue;"><b>Scope of Variable</b></h3>
<ul style="color:DodgerBlue;">
    <li>A variable created inside a function can only be accessed by statements inside that function, and ceases to exist when the function is exited.</li>
    <li>The variable is said to be local to the function or to have local scope.</li>
    <li>The same is true for the function’s parameters.
If variables created in two different functions have the same name, they have no relationship to each other; they are treated as completely different variables.</li>
    </ul>
    
-----------------------------

In [1]:
## program segment that demo the scope of variable

name = "Fred"    # variable that local to main body

def main():
    global name   # same as name in main body, changes alter the name that in the main body
    otherName = getName()
    name += otherName
    print (name)
    
def getName():
    name = "eric"  # this variable name is local to getName
    print (name)
    return name

## this part is the main body of this cell
print (name)
main()
print (name)


Fred
eric
Frederic
Frederic


----------------------

<h3 style="color:blue;"><b>Functions Returning Multiple Values</b></h3>
<ul style="color:DodgerBlue;">
    <li>Functions can return any type of object, not just a number, string, or Boolean value.</li>
    <li>The follow example is an instance of a function that return a tuple.</li>
    </ul>
    
------------------------

In [2]:
INTEREST_RATE = 0.04      # annual rate of interest

def main():
    ## Calculate the balance and interest earned from a savings account.
    principal = eval(input("Enter the amount of the deposit: "))
    numberOfYears = eval(input("Enter the number of years: "))
    (bal, intEarned) = balanceAndInterest(principal, numberOfYears)
    print("\nBalance        : ${0:,.2f}".format(bal))
    print("Interest Earned: ${0:,.2f}".format(intEarned))

def balanceAndInterest(prin, numYears):
    balance = prin * ((1 + INTEREST_RATE) ** numYears)
    interestEarned = balance - prin
    return (balance, interestEarned)


main()


Enter the amount of the deposit: 70000
Enter the number of years: 2

Balance        : $75,712.00
Interest Earned: $5,712.00


----------------------

<h3 style="color:blue;"><b>Functions Calling Other Functions</b></h3>
<ul style="color:DodgerBlue;">
    <li>A function can call another function.</li>
    <li>When the called function terminates (that is, after a return statement or the last statement of the called function is executed), the control returns to the place in the calling function just after where the function call occurred.</li>
    </ul>




<h3 style="color:blue;"><b>Function that Calling Itself</b></h3>
<ul style="color:DodgerBlue;">
    <li>Function that calling itself is known as recursive function.</li>
    <li>It is a very powerful function to solve some recurrence instances.</li>
    <li>Example:</li>
    <ol style="color:SlateBlue;">
        <li>determine a factorial</li>
        <li>determine the game tower-of-hanoi</li>
    </ol>
    </ul>
    
-----------------------------------------------

In [ ]:
## factorial function, ## this function accept any non-negative, 
## including zero with 0! = 1
def factorial(n):
    if n <= 1:
        print(1, end=" ")
        return 1
    else:
        print("{} x".format(n), end=" ")
        return(factorial(n-1))
    

In [ ]:
num = eval(input("Enter a non-negative, including zero: "))
print("{}! = ".format(num), end="")
factorial(num)
print("\n")


In [ ]:
## The game tower-of-hanoi
def towerOfHanoi(nDisc, fromP, toP, tempP):
    if nDisc <= 1:
        print("Move disc {} from {} to {}".format(nDisc, fromP, toP))
    else:
        towerOfHanoi(nDisc-1, fromP, tempP, toP)
        print("Move disc {} from {} to {}".format(nDisc, fromP, toP))
        towerOfHanoi(nDisc-1, tempP, toP, fromP)
        

In [ ]:
towerOfHanoi(3, "A", "C", "B")


----------------------

<h3 style="color:blue;"><b>Library Modules</b></h3>
<ul style="color:DodgerBlue;">
    <li>A variation of the import statement is</li>
    <span style="color:white;">.....</span><span style="color:brown;">from moduleName import *</span><br>
<li>After such a statement has been executed, any function from the module can be used directly without having to prepend it with the module name and a period.</li> 
    <li>This variation is most often employed when a program uses many functions from the module.</li>
    </ul>
    
----------------------------

In [3]:
import numpy as np   ## module of mathematical functions
import pandas as pd
import seaborn as sns
import scipy.stats as sts
import matplotlib as mpl
import matplotlib.pyplot as plt
import math
import random
import csv
import sys


In [4]:
student = ("Peter", "Calvin", "Steven", "Alan", "Debbie", \
          "Zoo", "Queenie", "Betty", "Don", "Ban", \
          "Lancy", "Mandy", "Terry", "Wendy", "Grace")


In [5]:
random.choice(student)


'Debbie'

In [6]:
random.choice(student)


'Terry'

In [7]:
random.choice(student)


'Terry'

In [8]:
math.floor(3.1417)


3

In [9]:
math.ceil(3.1417)


4

In [10]:
math.pow(3, 4)


81.0

In [11]:
np.arange(2,10) # create a list the have values from 2 to 10-1 inclusively


array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.full((3,4), 5) # create a 3x4 matrix that fill with 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
np.linspace(0,2,11) # evenly determine 11-1 segments from range 0 ~ 2


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

---------------------------

<h3 style="color:red;"><b>Student Practice</b></h3>
<p style="color:SlateBlue;">In the empty cells below, write a pay-raise program that enter a person's name,
and current monthly salary, and then displays the person's monthly salary next year (i.e. salary that after increment).
    People earning less than mop 30,000 a month will receive a 5% raise, and those earning mop 30,000 or more will receive a raise of mop 1,800 plus 2% of the amount over mop 30,000. Use functions for <span style="color:red;">input and output</span>, and a function to <span style="color:red;">calculate the new salary</span>.
</p>

-------------------------------

In [ ]:
## function to capture name, current monthly salary

def captureData():
    name = input ("Please enter your name:                   ")
    mSalary = eval(input("Please enter your current monthly salary: "))
    return (name, mSalary)


In [ ]:
## function to return the incremented Salary

def determineIncrement (salary):
    if salary < 30000:
        iSalary = salary * 1.05 
    else:
        iSalary = salary + 18000 + (salary - 30000) * 0.02
        
    return (iSalary)


In [ ]:
## function to out the name, current salary, and the incremented salary

def displaySalary (name, cSalary, iSalary):
    print ("\nName of Staff              : {}".format(name))
    print ("Your current monthly salary: ${:,.2f}".format(cSalary))
    print ("Your new monthly salary    : ${:,.2f}".format(iSalary))
    

In [ ]:
## the main program body that do the work by calling the relevant functions

# capture the data
(name, cSalary) = captureData()

# calculate the increment
iSalary = determineIncrement(cSalary)

# output the result
displaySalary(name, cSalary, iSalary)


---------------------------

<h3 style="color:red;"><b>Student Practice - CHALLENGE QUESTION</b></h3>
<p style="color:SlateBlue;">In the empty cell below, write a function to return the nth  Fibonacci number.</p>
<p style="color:slateBlue;">The Fibonacci Sequence is the series of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ..., the 1st term returns a 0, the 2nd returns a 1, and the 3rd term returns a 1, the 4th term returns a 2, and so on.
</p>

-------------------------------

In [2]:
## function fibonacci accept a non-negative and return the nth term of the fibonacci number
## the sequence started with 0th term.
def fibonacci(n = 0):
    if n == 0:
        num = 0
    elif n == 1:
        num = 1
    else:
        num = fibonacci(n-2)+fibonacci(n-1)

    return (num)
             

In [3]:
## get the nth fibonacci number
fibonacci(7)


13

---------------------

<h3 style="color:red;"><b>Student Practice - CHALLENGE QUESTION</b></h3>
<p style="color:SlateBlue;">In the empty cell below, write a function to generate the Fibonacci sequence.<br>
The Fibonacci sequence is the series of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ....</p>

---------------------

In [4]:
## generate the fibonacci sequence
term = eval(input("Enter the number of terms: "))
if term < 0:
    print("Invalid input!")
else:
    print ("\nThe requested Fibonacci sequence:")
    for i in range(0, term):
        print ("{}  ".format(fibonacci(i)), end ="")
    print ("\n")


Enter the number of terms: 7

The requested Fibonacci sequence:
0  1  1  2  3  5  8  

